[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4


# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/mraaroncruz"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mraaroncruz"
    weight = 3
